server:
  port: 9000
  context-path: /telecomsz

spring:
  application:
    name: telecomsz-platform

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000


eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:9010/cloud/eureka/

feign:
  client:
    config:
      feignName:
        connectTimeout: 10000
        readTimeout: 10000
      TELECOMSZ-PLATFORM-INTERFACE:
        connectTimeout: 10000
        readTimeout: 10000